# gnome desktop
gnome-python2-gconf
gnome-desktop
gnome-panel
gnome-session
gnome-terminal
metacity
nautilus

# allow switching from Sugar
olpc-switch-desktop

# GNOME dependencies. Listed explicitly to prevent equivalent components
# from other desktops being brought in instead
PolicyKit-gnome
notification-daemon

# battery applet
batti

# sound mixer/volume control (#10706)
gmixer

# internet
xulrunner
firefox
empathy

# office
abiword
gnumeric
evince

# graphics
eog
inkscape
gimp

# audio & video
audacity
totem
totem-gstreamer
totem-mozplugin

# more desktop stuff
file-roller
gedit
gnash-plugin
NetworkManager-gnome
xdg-user-dirs-gtk

