# gnome desktop
gnome-python2-gconf
gnome-desktop
gnome-panel
gnome-session
gnome-terminal
gnome-settings-daemon
metacity
nautilus

# allow switching from Sugar
olpc-switch-desktop

# GNOME dependencies. Listed explicitly to prevent equivalent components
# from other desktops being brought in instead
PolicyKit-gnome
notification-daemon

# internet
epiphany

# office
abiword
gnumeric
evince

# graphics
eog
inkscape
gimp

# audio & video
audacity
totem
totem-mozplugin

# more desktop stuff
file-roller
gedit
gnash-plugin
network-manager-applet
nm-connection-editor
xdg-user-dirs-gtk

